WEAVIATE_API_KEY = "nMZuw1z1zvtnjkXXOMGx90ws7YWGSsakItdus"
WEAVIATE_URL = "https://hha2nvjsruetknc5vxwrwa.c0.europe-west2.gcp.weaviate.cloud"
COHERE_API_KEY = "JaLagsYZvL2KgTDfuXBtifi4uGj8Qz07WUbrjNzq"
